# Render Blueprint for Chrysalis Backend
# This file automates the deployment process

services:
  - type: web
    name: chrysalis-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm run build:prod
    startCommand: npm start
    rootDir: server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      # Add your actual environment variables here
      # Copy from your local .env files
      - key: DATABASE_URL
        sync: false  # You'll need to add this manually
      - key: JWT_SECRET
        sync: false  # You'll need to add this manually
      - key: MAILGUN_API_KEY
        sync: false  # You'll need to add this manually
      - key: MAILGUN_DOMAIN
        sync: false  # You'll need to add this manually
      - key: CLOUDINARY_URL
        sync: false  # You'll need to add this manually
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # You'll need to add this manually
      - key: CLOUDINARY_API_KEY
        sync: false  # You'll need to add this manually
      - key: CLOUDINARY_API_SECRET
        sync: false  # You'll need to add this manually
      - key: FIREBASE_PROJECT_ID
        sync: false  # You'll need to add this manually
      - key: FIREBASE_API_KEY
        sync: false  # You'll need to add this manually
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false  # You'll need to add this manually
      - key: FIREBASE_APP_ID
        sync: false  # You'll need to add this manually
      - key: GA_MEASUREMENT_ID
        sync: false  # You'll need to add this manually
      - key: GA_STREAM_ID
        sync: false  # You'll need to add this manually
