name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build:frontend
    
    - name: Install backend dependencies
      run: cd server && npm ci
    
    - name: Build backend
      run: cd server && npm run build
    
    - name: Run backend tests
      run: cd server && npm test --if-present
      
    - name: Build status
      run: echo "✅ Build completed successfully - ready for Render auto-deploy"
